export type Transaction = {
    id?: number | null,
    name?: string | null,
    amount?: number | null,
    datetime?: string | null
};

export type Rule = {
    id?: number | null,
    title: string | null,
    description?: string | null,
    rule: object[] | null,
    weight: number | null,
    autogenerated: boolean,
    active: boolean,
    createdAt: string | null
}

export const emptyTransactionRecord: Transaction = {
    id: null,
    name: null,
    amount: null,
    datetime: null
}

const currentDateTime = (): string => {
    return new Date().toISOString();
}

export const emptyRuleRecord: Rule = {
    id: null,
    title: '',
    description: '',
    rule: [],
    weight: null,
    autogenerated: false,
    active: true,
    createdAt: currentDateTime()
}