export type Transaction = {
    id?: number | null,
    name?: string | null,
    amount?: number | null,
    datetime?: string | null
};

export type RuleItem = {
    type: string,
    value: string | number
}

export type Rule = {
    id?: number | null,
    title: string | null,
    description?: string | null,
    rule: RuleItem[] | null,
    weight: number | null,
    autogenerated: boolean,
    active: boolean,
    createdAt: string | null
}

export const emptyTransactionRecord: Transaction = {
    id: null,
    name: null,
    amount: null,
    datetime: null
}

export const emptyRuleItem = (): RuleItem=> {
    return { type:'', value: ''}
}

const currentDateTime = (): string => {
    return new Date().toISOString();
}

export const emptyRuleRecord: Rule = {
    id: null,
    title: '',
    description: '',
    rule: [(emptyRuleItem())],
    weight: null,
    autogenerated: false,
    active: true,
    createdAt: currentDateTime()
}

export type colDef = {
    field: string;
}

export type MatSelectOption = {
  label: string;
  value: number | string;
};