import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import {
  FormBuilder,
  FormGroup,
  Validators,
  FormGroupDirective,
} from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { MatDialog } from '@angular/material/dialog';
import { Clipboard } from '@angular/cdk/clipboard';
import { emptyRuleRecord, emptyTransactionRecord, Rule, Transaction } from 'src/app/models';

@Component({
  selector: 'app-rule-form',
  templateUrl: './rule-form.component.html',
  styleUrls: [
    './rule-form.component.scss',

  ],
})
export class RuleFormComponent implements OnInit {
  formSubmitting: boolean = false;
  ruleForm: FormGroup;

  constructor(
    private location: Location,
    private route: ActivatedRoute,
    private fb: FormBuilder,
    public dialog: MatDialog,
    public clipboard: Clipboard
  ) {
    this.ruleForm = this.setupRuleFormGroup();
  }

  setupRuleFormGroup = (
    ruleFormRecord: Rule = emptyRuleRecord
  ): FormGroup => {
    return this.fb.group({
      id: [ruleFormRecord?.id],
      title: [ruleFormRecord?.title, Validators.required],
      description: [ruleFormRecord?.description],
      rule: [ruleFormRecord?.rule],
      weight: [ruleFormRecord?.weight],
      autogenerated: [ruleFormRecord?.autogenerated],
      active: [ruleFormRecord?.active]
    });
  };



  ngOnInit(): void {

  }


  goBack() {
    this.location.back();
  }


  submitForm(form: FormGroup, formDirective: FormGroupDirective) {
    this.formSubmitting = true;
  }
}